version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/carhartt_platform
    overwrite: true # 기존 파일 덮어씌움

  # 현재는 학습 목적이니 root 계정으로 spring boot 배포 파일을
  # 실행하지만 실무에선 각 역할마다 전용 계정을 만들어서 필요한
  # 권한만 부여한 후 사용하는 것이 일반적이다
  # sudo adduser springboot --disabled-password --gecos ""
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/deploy.sh # 실행할 스크립트
      timeout: 60
      runas: root
