spring:
  security:
    oauth2:
      client:
        # OAuth2 인증 제공자에 대한 설정 정보를 포함
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
        # 클라이언트 애플리케이션(Spring Boot)에 대한 설정을 포함
        registration:
          kakao:
            # client-id, client-secret, reditect-uri는 직접 넣어주어야 함
            # client-id: 47162626b8cb908fea4e03439449674e
            client-id: 1370abe0c0f726b791502518bd0e12ff # test 전용
            # client-secret: 8BJ54MXf9npEfzE2w6op4dVamJUEe5fr
            client-secret: G6hY7ybVPZ9EjfIvJRwuJqD2Nyv2vmx2 # local test 전용
            redirect-uri: http://43.203.218.247/oauth/kakao/callback
            # redirect-uri: http://localhost:8080/v1/oauth/kakao/callback # local test 전용
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - name
              - account_email