# local 메타 정보
app:
  base-url: http://localhost:8080/v1/
  identifier : local
  front-callback-path : empty

# local 세션 관련 설정
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        same-site: lax

# oauth 정보 설정
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
        registration:
          kakao:
            # client-id, client-secret, reditect-uri는 직접 넣어주어야 함
            # client-id: 47162626b8cb908fea4e03439449674e
            client-id: 1370abe0c0f726b791502518bd0e12ff
            # client-secret: 8BJ54MXf9npEfzE2w6op4dVamJUEe5fr
            client-secret: G6hY7ybVPZ9EjfIvJRwuJqD2Nyv2vmx2
            redirect-uri : http://localhost:8080/v1/oauth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - name
              - account_email
