# prod 메타 정보
app:
  base-url: https://carhartt-usedtransactions.com/v1/
  identifier : prod
  front-callback-path : /login/callback

# prod 세션 관련 설정
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: true
        same-site: none
  # 프록시가 붙여주는 헤더들을 spring이 신뢰하도록 하는 설정
  forward-headers-strategy: framework



# prod 세션 관련 설정
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
        registration:
          kakao:
            client-id: 1370abe0c0f726b791502518bd0e12ff
            client-secret: G6hY7ybVPZ9EjfIvJRwuJqD2Nyv2vmx2
            redirect-uri : https://carhartt-usedtransactions.com/v1/oauth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - name
              - account_email