# Common Settings
spring.application.name=C_platform

# Message Configuration
spring.messages.basename=messages,messages_errors
spring.messages.encoding=UTF-8

# Profile Import
spring.config.import=optional:classpath:application-${spring.profiles.active}.yml

# Server Configuration
server.port=8080

# Logging
spring.output.ansi.enabled=ALWAYS
