# prod 메타 정보
app:
  base-url: https://carhartt-usedtransactions.com/v1/
  identifier : prod
  front-callback-path : /login/callback

# prod 세션 관련 설정
# domain을 생략하면 default로 Host-Only 설정
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: true
        same-site: none
        path: /
  # 프록시가 붙여주는 헤더들을 spring이 신뢰하도록 하는 설정
  forward-headers-strategy: framework


# prod 세션 관련 설정
spring:
  messages:
    encoding: UTF-8
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

        registration:
          kakao:
            client-id: 1370abe0c0f726b791502518bd0e12ff
            client-secret: G6hY7ybVPZ9EjfIvJRwuJqD2Nyv2vmx2
            redirect-uri : https://carhartt-usedtransactions.com/v1/oauth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - name
              - account_email
          naver: # 정리 필요
            # client-id: v2MpZi1jsRTED3WGkHcw (운영용)
            # client-secret: R8ppGlLLEG (운영용)
            client-id: v2MpZi1jsRTED3WGkHcw
            client-secret: R8ppGlLLEG
            redirect-uri: https://carhartt-usedtransactions.com/v1/oauth/naver/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: naver
            scope: # Resource server에 받고자 하는 사용자 정보 범위
              - nickname
              - email